# Generated by Django 5.2 on 2025-06-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
